# filename: config-template.yaml
init_crypto: false
reset_epoch: true

# current server ip
local_server_ip: ${local_server_ip}

# the servers that will be used
server_ips: [${block_server_0_ip}, ${block_server_1_ip}]

epoch_ips: [${epoch_server_0_ip}]

#cc_type: ycsb
cc_type: ${cc_type}

# user send invoke tx to all server in server_ips, otherwise send to local_server_ip.
# crypto helper init all user pri-pub keys
send_to_all_client_proxy: true

# turn this off can improve performance a little
tr_manager_show_categorize_detail: true
# by turning this off, blk server can recovering fastly from receiving too much aborted tx
tr_manager_reuse_abort_transaction: false

aggregation:
  enable: ${aggregation_enable_flag}
  policy: 0
  #policy: 5
  cluster_ips: [${aggregation_block_server_0_ip}, ${aggregation_block_server_1_ip}]

heart_beat_config:
  table_name: heart_beat_table
  func_name: empty
  reads: 0
  writes: 0

# all of servers info
# note: path may not be the same
server_data:
  ${block_server_0_ip}:
    public_crt: crypto/server.1.public.key
    private_crt: crypto/server.1.private.key
    user_public_crt: crypto/server.1.public.user.key
    user_private_crt: crypto/server.1.private.user.key
  ${block_server_1_ip}:
    public_crt: crypto/server.2.public.key
    private_crt: crypto/server.2.private.key
    user_public_crt: crypto/server.2.public.user.key
    user_private_crt: crypto/server.2.private.user.key
  ${block_server_2_ip}:
    public_crt: crypto/server.3.public.key
    private_crt: crypto/server.3.private.key
    user_public_crt: crypto/server.3.public.user.key
    user_private_crt: crypto/server.3.private.user.key

#epoch server cert
epoch_data:
  public_crt: crypto/epoch.public.key
  private_crt: crypto/epoch.private.key

# Yahoo! Cloud System Benchmark
# Workload A: Update heavy workload
#   Application example: Session store recording recent actions
#
#   Read/update ratio: 50/50
#   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
#   Request distribution: zipfian
#cc_config:
cc_config_a:
  table_name: user_table
  field_count: 10
  field_length_distribution: constant
  #field_length_distribution: uniform
  #field_length_distribution: zipfian
  field_length: 100
  max_scan_len: 1000
  scan_len_distribution: uniform
  #scan_len_distribution: zipfian
  insert_start: 0
  # this is the shew factor, default: 0.99
  zipfian_const: 0.99
  # inserts order default: hashed
  ordered_inserts: false
  record_count: 1000000
  operation_count: 10000
  read_all_fields: true
  write_all_fields: false
  read_proportion: 0.00
  update_proportion: 1.00
  insert_proportion: 0.00
  scan_proportion: 0.00
  read_modify_write_proportion: 0.0
  #request_distribution: uniform
  request_distribution: zipfian
  #request_distribution: latest

# Yahoo! Cloud System Benchmark
# Workload B: Read mostly workload
#   Application example: photo tagging; add a tag is an update, but most operations are to read tags
#
#   Read/update ratio: 95/5
#   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
#   Request distribution: zipfian
#cc_config:
cc_config_b:
  table_name: user_table
  field_count: 10
  field_length_distribution: constant
  #field_length_distribution: uniform
  #field_length_distribution: zipfian
  field_length: 100
  max_scan_len: 1000
  scan_len_distribution: uniform
  #scan_len_distribution: zipfian
  insert_start: 0
  # this is the shew factor, default: 0.99
  zipfian_const: 0.99
  # inserts order default: hashed
  ordered_inserts: false
  record_count: 10000
  operation_count: 10000
  read_all_fields: true
  write_all_fields: false
  read_proportion: 0.95
  update_proportion: 0.05
  insert_proportion: 0.00
  scan_proportion: 0.00
  read_modify_write_proportion: 0.0
  #request_distribution: uniform
  request_distribution: zipfian
  #request_distribution: latest

# Yahoo! Cloud System Benchmark
# Workload C: Read only
#   Application example: user profile cache, where profiles are constructed elsewhere (e.g., Hadoop)
#
#   Read/update ratio: 100/0
#   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
#   Request distribution: zipfian
#cc_config:
cc_config_c:
  table_name: user_table
  field_count: 10
  field_length_distribution: constant
  #field_length_distribution: uniform
  #field_length_distribution: zipfian
  field_length: 100
  max_scan_len: 1000
  scan_len_distribution: uniform
  #scan_len_distribution: zipfian
  insert_start: 0
  # this is the shew factor, default: 0.99
  zipfian_const: 0.99
  # inserts order default: hashed
  ordered_inserts: false
  record_count: 10000
  operation_count: 10000
  read_all_fields: true
  write_all_fields: false
  read_proportion: 1.00
  update_proportion: 0.00
  insert_proportion: 0.00
  scan_proportion: 0.00
  read_modify_write_proportion: 0.0
  #request_distribution: uniform
  request_distribution: zipfian
  #request_distribution: latest

# Yahoo! Cloud System Benchmark
# Workload D: Read latest workload
#   Application example: user status updates; people want to read the latest
#
#   Read/update/insert ratio: 95/0/5
#   Default data size: 1 KB records (10 fields, 100 bytes each, plus key)
#   Request distribution: latest

# The insert order for this is hashed, not ordered. The "latest" items may be
# scattered around the keyspace if they are keyed by userid.timestamp. A workload
# which orders items purely by time, and demands the latest, is very different than
# workload here (which we believe is more typical of how people build systems.)
#cc_config:
cc_config_d:
  table_name: user_table
  field_count: 10
  field_length_distribution: constant
  #field_length_distribution: uniform
  #field_length_distribution: zipfian
  field_length: 100
  max_scan_len: 1000
  scan_len_distribution: uniform
  #scan_len_distribution: zipfian
  insert_start: 0
  # this is the shew factor, default: 0.99
  zipfian_const: 0.99
  # inserts order default: hashed
  ordered_inserts: false
  record_count: 10000
  operation_count: 10000
  read_all_fields: true
  write_all_fields: false
  read_proportion: 0.95
  update_proportion: 0.00
  insert_proportion: 0.05
  scan_proportion: 0.00
  read_modify_write_proportion: 0.0
  #request_distribution: uniform
  #request_distribution: zipfian
  request_distribution: latest